FROM nikolaik/python-nodejs:python3.10-nodejs20-bullseye

RUN sudo apt-get install zsh
RUN sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
RUN sudo apt-get magic-wormhole

